server:
  port: 8080

spring:
  application:
    name: gearstock-erp
  datasource:
    url: jdbc:postgresql://localhost:5432/gearstockdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yR2VhclN0b2NrRVJQUHJvSldUQXV0aGVudGljYXRpb24yMDI2
  expiration: 86400000

logging:
  level:
    root: INFO
    com.gearstock: INFO
